# Generated by Django 2.2 on 2023-07-11 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=75)),
                ('lon', models.CharField(max_length=75)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
            ],
        ),
    ]
