# Generated by Django 2.2 on 2023-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='detailing_type',
            field=models.CharField(choices=[('Current weather', 'Current weather'), ('Minute forecast for 1 hour', 'Minute forecast for 1 hour'), ('Hourly forecast for 48 hours', 'Hourly forecast for 48 hours'), ('Daily forecast for 7 days', 'Daily forecast for 7 days')], default='Current weather', max_length=35),
        ),
    ]
